const mockModuleData = [
    {
        ModuleId: 1,
        ModuleName: "Sample Module 1",
        ModuleAuthorId: 123,
        ModuleDownloads: 50,
        ModuleShortDescription: "This is a sample module 1.",
        ModuleMarkdown: "## Sample Module 1\n\nThis is a sample module 1 content.",
        ModuleCreatedAt: "2023-08-28 12:00:00",
        ModuleUpdatedAt: "2023-08-28 12:00:00",
    },
    {
        ModuleId: 2,
        ModuleName: "Sample Module 2",
        ModuleAuthorId: 456,
        ModuleDownloads: 75,
        ModuleShortDescription: "This is a sample module 2.",
        ModuleMarkdown: "## Sample Module 2\n\nThis is a sample module 2 content.",
        ModuleCreatedAt: "2023-08-29 10:30:00",
        ModuleUpdatedAt: "2023-08-29 10:30:00",
    },
    {
        ModuleId: 3,
        ModuleName: "Sample Module 3",
        ModuleAuthorId: 789,
        ModuleDownloads: 30,
        ModuleShortDescription: "This is a sample module 3.",
        ModuleMarkdown: "## Sample Module 3\n\nThis is a sample module 3 content.",
        ModuleCreatedAt: "2023-08-30 14:45:00",
        ModuleUpdatedAt: "2023-08-30 14:45:00",
    },
    {
        ModuleId: 4,
        ModuleName: "Sample Module 4",
        ModuleAuthorId: 101,
        ModuleDownloads: 20,
        ModuleShortDescription: "This is a sample module 4.",
        ModuleMarkdown: "## Sample Module 4\n\nThis is a sample module 4 content.",
        ModuleCreatedAt: "2023-08-31 08:20:00",
        ModuleUpdatedAt: "2023-08-31 08:20:00",
    },
    {
        ModuleId: 5,
        ModuleName: "Sample Module 5",
        ModuleAuthorId: 202,
        ModuleDownloads: 90,
        ModuleShortDescription: "This is a sample module 5.",
        ModuleMarkdown: "## Sample Module 5\n\nThis is a sample module 5 content.",
        ModuleCreatedAt: "2023-09-01 16:10:00",
        ModuleUpdatedAt: "2023-09-01 16:10:00",
    },
];

export default mockModuleData;
